### ISSUE TITLE
Design Document Submitted

### ISSUE THREAD

**Issue by harwooja** [harwooja/CAPSTONE#1]
Inside docs

**Comment by szymczdm** [comment]
Did your team switch repositories? I had github.com/Jimicy/capstone.git as your repo.

**Comment by harwooja** [comment]
@szymczdm Yes we did.

**Comment by szymczdm** [comment]
You shouldn't be switching repos, but if you do, please send me an email and let me know ahead of time. Your doc is being marked now.
